# CI de Nível 01 - Disparo Manual através de clique

# nome da pipeline
name: "Execução Manual"

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch

on:
    workflow_dispatch:

#tarefas dentro da pipeline = jobs

jobs:
    #nome do job
    e2e-tests:
        # maquina onde o job vai rodar
        runs-on: ubuntu-latest

        # passos do job
        steps:
            # clone do projeto
            - uses: actions/checkout@v4

            # instalção do node
            - uses: actions/setup-node@v4
              with:
                  node-version: 24.x

            # instalação do Yarn
            - name: Instalando Yarn
              run: npm install -g yarn
            
            #   instalação das dependências
            - name: Instalando dependências
              run: yarn
            
            # instalação dos Browsers do Playwright
            - name: Instalando Browsers do Playwright
              run: yarn playwright install

            # criação de pasta para salvar arquivos utilizados para o relatório
            - name: Criando pasta ctrf
              run: mkdir -p ctrf
            
            # executar os testes e2e
            - name: Executando testes e2e
              run: yarn run e2e

            # publicação de relatório - Exercício 2: Implementando plugin/action disponível no Marketplace
            - name: Publicando reporte de testes
              uses: ctrf-io/github-test-reporter@v1
              with: 
                report-path: './ctrf/*.json'
                summary-delta-report: true
                tests-changed-report: true
                test-report: true
                failed-report: true
                fail-rate-report: true
                flaky-report: true
                flaky-rate-report: true
                failed-folded-report: true
                previous-results-report: true
                insights-report: true
                slowest-report: true
                skipped-report: true
                suite-folded-report: true
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: always()